# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Docs Home
    url: "https://madlabatuci.github.io/docs/"
    weight: 5
  - name: MPLib.js
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Showcase
    url: showcase/
    weight: 40
  - name: Community
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: Navigate MADLAB
    params:
      type: separator
    weight: 1
  - identifier: msteyvers
    name: "ğŸ§‘â€ğŸ« Dr. Mark Steyvers"
    url: "https://steyvers.socsci.uci.edu/"
    weight: 2
  - identifier: webpage
    name: "ğŸŒ MADLAB Webpage"
    url: "https://steyvers.socsci.uci.edu/madlab/"
    weight: 3
  - identifier: maindocs
    name: "ğŸ“– Documentation Home"
    url: ""
    weight: 4
